ROLE_KEYWORDS = [
    "ENGINEER",
    "DEVELOPER",
    "INTERN",
    "ANALYST",
    "CONSULTANT",
    "ASSOCIATE",
    "SCIENTIST",
    "MANAGER",
    "LEAD",
    "ARCHITECT",
    "SPECIALIST",
    "TECHNICIAN",
]
