SECTION_HEADERS = [
    'EDUCATION',
    'EXPERIENCE',
    'PROJECTS',
    'ACHIEVEMENTS',
    'CERTIFICATIONS',
    'PUBLICATIONS',
    "SKILLS",
    "TECHNICAL SKILLS", 
    "TECHNICAL SKILLS :",
    "SUMMARY",
    "PROFESSIONAL EXPERIENCE",
    "WORK EXPERIENCE"
]

SKILL = [
    "SKILLS","TECHNICAL SKILLS", "TECHNICAL SKILLS :"
]
SKILL_CATEGORY_HEADERS = [
    "PROGRAMMING LANGUAGES",
    "LANGUAGES",
    "FRAMEWORKS",
    "LIBRARIES",
    "DATABASES",
    "TOOLS",
    "TECHNOLOGIES",
    "TECHNOLOGIES & TOOLS"
]
PROJECT_HEADERS = [
    'PROJECTS',
    'PROJECTS :'
]
EDUCATION_SECTION_HEADERS  = ["EDUCATION"]

EXPERIENCE_HEADERS = ['EXPERIENCE']