SECTION_HEADERS = [
    'EDUCATION',
    'EXPERIENCE',
    'PROJECTS',
    'ACHIEVEMENTS',
    'CERTIFICATIONS',
    'PUBLICATIONS',
    'LANGUAGES'
]

SKILL = [
    "SKILLS","TECHNICAL SKILLS", "TECHNICAL SKILLS :"
]

EDUCATION_SECTION_HEADERS  = ["EDUCATION"]

EXPERIENCE_HEADERS = ['EXPERIENCE']