SECTION_HEADERS = [
    'EDUCATION',
    'EXPERIENCE',
    'PROJECTS',
    'ACHIEVEMENTS',
    'CERTIFICATIONS',
    'PUBLICATIONS',
    'LANGUAGES'
]

SKILL = [
    "SKILLS","TECHNICAL SKILLS", "TECHNICAL SKILLS :"
]
EDUCATION_SECTION_HEADERS  = ["EDUCATION"]

INSTITUTION_KEYWORDS = [
    "SCHOOL",
    "COLLEGE",
    "INSTITUTE",
    "UNIVERSITY",
    "ACADEMY",
]

COMPANY_KEYWORDS = [
    "PVT",
    "PRIVATE",
    "LIMITED",
    "LTD",
    "LLP",
    "INC",
    "CORP",
    "TECHNOLOGIES",
    "SOLUTIONS",
    "SYSTEMS",
]

EXPERIENCE_HEADERS = ['EXPERIENCE']